all: libbitmsghash.so

powtest:
	./testpow.py

libbitmsghash.so: bitmsghash.o
	${CXX} bitmsghash.o -shared -fPIC -lpthread -lcrypto $(LDFLAGS) -o libbitmsghash.so

bitmsghash.o:
	${CXX} -Wall -O3 -march=native -fPIC $(CCFLAGS) -c bitmsghash.cpp

clean:
	rm -f bitmsghash.o libbitmsghash.so

